### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by georgecodes**
I've made some dependencies clear.

### CODE REVIEW

**Comment by jimmidyson** [comment]
Thanks @georgecodes!

**Comment by georgecodes** [comment]
No problem. And I'm sorry for all the names I called you a few minutes ago, before I figured this out. Well. Mostly sorry. For some of them. A bit.

I'm not sorry.

**Comment by jimmidyson** [comment]
That's mostly fine. Apart from that last name you called me - that was just a step too far.

**Comment by georgecodes** [comment]
What, "Jimmi"?

**Pull request merged**
